ssh_port: "22"
packages_list:
  - pwgen
  - openjdk-11-jre-headless
  - default-jdk
client_bin_url: "https://www.jelurida.com/ardor-client.zip"
client_bin_archive: "ardor-client.zip"
chain_db_url: "https://www.jelurida.com/Ardor-nxt_db.zip"
chain_db_archive: "Ardor-nxt_db.zip"
node_download_folder: "/tmp"
node_user: "ardor"
node_group: "ardor"
node_home: "/home/ardor"
node_db_home: "{{ node_home }}/ardor"
node_config_file: "nxt.properties"
node_config_folder: "{{ node_db_home }}/conf"
node_service_name: "ardor"
node_service_file: "/etc/systemd/system/{{ node_service_name }}.service"
ardor_my_platform: "UNDEFINED"
firewall_policies:
    - { direction: 'incoming', policy: 'deny' }
    - { direction: 'outgoing', policy: 'allow' }
firewall_rules:
    - { rule: 'limit', port: '{{ ssh_port | default("22") }}', proto: 'tcp', comment: "Secure Shell Access" }
    - { rule: 'allow', port: '27874', proto: 'tcp', comment: "Ardor Node Peer Port" }
    - { rule: 'allow', port: '27876', proto: 'tcp', comment: "Ardor Node API Port" }